variable "stack_config" {
  type = object({
    rke2_version                        = string
    calico_version                      = string
    rke2_cni                            = string
    install_kubevirt                    = bool
    install_custom_kubectl = bool
    libvirt_network_name                = string
    libvirt_network_mode                = string
    libvirt_network_domain              = string
    libvirt_network_addresses           = list(string)
    libvirt_network_bridge_name         = string
    libvirt_network_gateway             = string
    libvirt_network_dns_servers         = list(string)
    libvirt_cloudinit_disk_masters_name = string
    libvirt_cloudinit_disk_agents_name  = string
    libvirt_volume_masters_disk_name    = string
    libvirt_volume_masters_disk_pool    = string
    libvirt_volume_masters_disk_size    = number
    libvirt_volume_masters_disk_format  = string
    libvirt_network_masters_ips         = list(string)
    libvirt_domain_masters_name         = string
    libvirt_domain_masters_memory       = number
    libvirt_domain_masters_vcpu         = number
    libvirt_volume_agents_disk_name     = string
    libvirt_volume_agents_disk_pool     = string
    libvirt_volume_agents_disk_size     = number
    libvirt_volume_agents_disk_format   = string
    libvirt_network_agents_ips          = list(string)
    libvirt_domain_agents_name          = string
    libvirt_domain_agents_memory        = number
    libvirt_domain_agents_vcpu          = number
  })
  default = {
    rke2_version                        = "v1.30.9+rke2r1"
    calico_version                      = "v3.29.2"
    rke2_cni                            = "none"
    install_kubevirt                    = true
    install_custom_kubectl = true
    libvirt_network_name                = "rke2_network"
    libvirt_network_mode                = "nat"
    libvirt_network_domain              = "rke2.local"
    libvirt_network_addresses           = ["192.168.122.0/24"]
    libvirt_network_bridge_name         = "virbr0"
    libvirt_network_gateway             = "192.168.122.1"
    libvirt_network_dns_servers         = ["8.8.8.8", "8.8.4.4"]
    libvirt_cloudinit_disk_masters_name = "rke2-master-init"
    libvirt_cloudinit_disk_agents_name  = "rke2-agent-init"
    libvirt_volume_masters_disk_name    = "rke2-master-disk"
    libvirt_volume_masters_disk_pool    = "rke2"
    libvirt_volume_masters_disk_size    = 53687091200 # 50GB 21474836480 # 20GB
    libvirt_volume_masters_disk_format  = "qcow2"
    libvirt_network_masters_ips         = ["192.168.122.10", "192.168.122.11", "192.168.122.12"]
    libvirt_domain_masters_name         = "rke2-master"
    libvirt_domain_masters_memory       = 8192 # 4GB
    libvirt_domain_masters_vcpu         = 4
    libvirt_volume_agents_disk_name     = "rke2-agent-disk"
    libvirt_volume_agents_disk_pool     = "default"
    libvirt_volume_agents_disk_size     = 42949672960 # 40GB 21474836480 # 20GB 
    libvirt_volume_agents_disk_format   = "qcow2"
    libvirt_network_agents_ips          = ["192.168.122.13", "192.168.122.14"]
    libvirt_domain_agents_name          = "rke2-agent"
    libvirt_domain_agents_memory        = 4096 # 4GB
    libvirt_domain_agents_vcpu          = 2
  }
}
